import type { Metadata } from "next";
import { Inter, Trispace, Roboto_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/ui/navbar";
import { Separator } from "@/components/ui/separator";

const inter = Roboto_Mono({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} mx-2 md:mx-4 xl:mx-10 2xl:mx-48 bg-gray-950`}>
        <Navbar />
        {/* <Separator orientation="vertical" className="" /> */}
        {children}
      </body>
    </html>
  );
}
