import type { Metadata } from "next";
import { Inter, Trispace, Roboto_Mono, Orbitron } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/ui/navbar";
import Footer from "@/components/ui/footer";
import { Separator } from "@/components/ui/separator";

// const inter = Inter({subsets: ["latin"]});
const robotoMono = Roboto_Mono({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={robotoMono.className}>
      <body className={`px-2 md:px-4 xl:px-10 2xl:px-48 bg-gray-950 antialiased flex flex-col h-screen`}>
        <Navbar />
        <div className="flex-1">
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
