import type { Metadata } from "next";
import { Inter, Trispace, Roboto_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/ui/navbar";
import Footer from "@/components/ui/footer";
import { Separator } from "@/components/ui/separator";

const inter = Inter({subsets: ["latin"]});
const roboto = Trispace({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={roboto.className}>
      <body className={`px-2 md:px-4 xl:px-10 2xl:px-48 bg-gray-950 antialiased`}>
        <Navbar />
        {/* <Separator orientation="vertical" className="" /> */}
        {children}
        <Footer />
      </body>
    </html>
  );
}
